config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :passengers
  resources :bookings
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    namespace :active_storage do
      resources :variant_records
    end
    namespace :active_storage do
      resources :attachments
    end
    namespace :active_storage do
      resources :blobs
    end
    resources :users
    resources :services
    resources :notifications
    resources :announcements
    root to: "dashboard#show"
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  # resources :bookings
  # resources :passengers
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # resources :flights, only: [:index]
  root to: 'flights#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, class_name: "Airport", foreign_key: "from_id"
  belongs_to :to_airport, class_name: "Airport", foreign_key: "to_id"
  has_many :bookings
  has_many :passengers, through: :bookings
  accepts_nested_attributes_for :bookings
end

app/controllers/flight_controller.rb
class FlightController < ApplicationController
  def index
    @flights = Flight.all
    @airports = Airport.all
    @select_airports = Airport.all.map { |airport| [airport.city, airport.airport_code, airport.id] }
  end

  # def search
  #   @search = params["search"]
  # end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @search = params["search"]
    @select_dates = Flight.all.order(date: :asc).map { |flight| [flight.date, flight.date] }
    @select_dates = @select_dates.uniq
    @select_airports = Airport.all.map { |airport| [airport.city, airport.id] }
    if @search.present?
      @passengers = @search.values[2]
      @available_flights = Flight.where("from_id = :from_airport AND to_id = :to_airport AND date = :date", {from_airport: @search.values[0], to_airport: @search.values[1], date: @search.values[3]})
      @available_flights = @available_flights.order(time: :asc)
      @search.values.map do |param|
        if param.blank?
          @search = nil
          root_path
          flash.now[:alert] = "Invalid search! Make sure to select an option for every form." if param.blank?
        end
      end
    end
  end
end

app/helpers/flight_helper.rb
module FlightHelper
end

app/views/flights/_available_flights.erb
<br>
<h1>Available Flights</h1>
<% unless @available_flights.empty? %>
  <br>
  <%= simple_form_for :booking, url: new_booking_path, method: "GET", defaults: { input_html: { class: 'col-md-1' } } do |f| %>

    <div class="row">
      <h5>
        <div class="px-3 pb-3">
          <%= @available_flights.first.from_airport.city %> (<%= @available_flights.first.from_airport.airport_code %>)
          ->
          <%= @available_flights.first.to_airport.city %> (<%= @available_flights.first.to_airport.airport_code %>)
          on
          <%= @available_flights.first.date %>
        </div>

        <%= f.hidden_field :flight_id, :value => "#{@available_flights.first.id}" %>
        <%= f.hidden_field :passengers, :value => "#{@passengers}" %>

        <div class="col-md-3 p-3">
          <div class="form-inputs pb-3">
            <%= f.input_field :time, as: :radio_buttons, collection: @available_flights.map { |f| f.time } %>
          </div>
        </div>

        <div class="col px-3">
          <div class="btn btn-primary text-white">
            <%= f.button :submit, "Proceed", class: 'col btn btn-primary' %>
          </div>
        </div>
      </h5>
    </div>
  <% end %>
<% else %>
  No available flights.
<% end %>

app/views/flights/_flights_available.erb
<br>
<h1>Available Flights</h1>
<% unless @available_flights.empty? %>
  <br>
  <%= simple_form_for :booking, url: new_booking_path, method: "GET", defaults: { input_html: { class: 'col-md-1' } } do |f| %>

    <div class="row">
      <h5>
        <div class="px-3 pb-3">
          <%= @available_flights.first.from_airport.city %> (<%= @available_flights.first.from_airport.airport_code %>)
          ->
          <%= @available_flights.first.to_airport.city %> (<%= @available_flights.first.to_airport.airport_code %>)
          on
          <%= @available_flights.first.date %>
        </div>

        <%= f.hidden_field :flight_id, :value => "#{@available_flights.first.id}" %>
        <%= f.hidden_field :passengers, :value => "#{@passengers}" %>

        <div class="col-md-3 p-3">
          <div class="form-inputs pb-3">
            <%= f.input_field :time, as: :radio_buttons, collection: @available_flights.map { |f| f.time } %>
          </div>
        </div>

        <div class="col px-3">
          <div class="btn btn-primary text-white">
            <%= f.button :submit, "Proceed", class: 'col btn btn-primary' %>
          </div>
        </div>
      </h5>
    </div>
  <% end %>
<% else %>
  No available flights.
<% end %>

app/views/flights/_select_form.erb
<div class="container">
  <% unless @search.present? %>
    <%= simple_form_for :search, url: root_path, method: "GET" do |f| %>

      <div class="row">
        <div class="col-md-3 py-2">
          <div class="py-3">
            <%= f.input :from_id, as: :select, collection: @select_airports, prompt: 'From', label: false %>
          </div>
        </div>

        <div class="col-md-3 py-2">
          <div class="py-3">
            <%= f.input :to_id, as: :select, collection: @select_airports, prompt: 'To', label: false %>
          </div>
        </div>

        <div class="col-md-2 py-2">
          <div class="py-3">
            <%= f.input :passengers, as: :select, collection: 1..4, prompt: 'Passengers', label: false %>
          </div>
        </div>

        <div class="col-md-2 py-2">
          <div class="py-3">
            <%= f.input :datetime, as: :select, collection: @select_dates, prompt: 'Date', label: false %>
          </div>
        </div>

        <div class="col-md-2 py-2">
          <div class="py-3">
            <%= f.button :submit, "Search Flights", class: 'col btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/flights/index.html.erb
<h1>Flights</h1>
<br>
<% if @search.present? && @available_flights.present? %>
  <% @search = nil %>
  <%= render 'select_form' %>
  <%= render 'available_flights' %>
<% else %>
  <%= render 'select_form' %>
<% end %>