config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :passengers
  resources :bookings
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    namespace :active_storage do
      resources :variant_records
    end
    namespace :active_storage do
      resources :attachments
    end
    namespace :active_storage do
      resources :blobs
    end
    resources :users
    resources :services
    resources :notifications
    resources :announcements
    root to: "dashboard#show"
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  # resources :bookings
  # resources :passengers
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # resources :flights, only: [:index]
  root to: 'flights#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :set_passenger, only: %i[ show edit update destroy ]

  # GET /passengers or /passengers.json
  def index
    @passengers = Passenger.all
  end

  # GET /passengers/1 or /passengers/1.json
  def show
  end

  # GET /passengers/new
  def new
    @passenger = Passenger.new
    @flight = Flight.find(params["booking"]['flight_id'])
  end

  # GET /passengers/1/edit
  def edit
  end

  # POST /passengers or /passengers.json
  def create
    @passenger = Passenger.new(passenger_params)

    respond_to do |format|
      if @passenger.save
        format.html { redirect_to @passenger, notice: "Passenger was successfully created." }
        format.json { render :show, status: :created, location: @passenger }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passengers/1 or /passengers/1.json
  def update
    respond_to do |format|
      if @passenger.update(passenger_params)
        format.html { redirect_to @passenger, notice: "Passenger was successfully updated." }
        format.json { render :show, status: :ok, location: @passenger }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passengers/1 or /passengers/1.json
  def destroy
    @passenger.destroy
    respond_to do |format|
      format.html { redirect_to passengers_url, notice: "Passenger was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def passenger_params
      params.require(:passenger).permit(:flight_id, :name, :email, :booking_id)
    end
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/passengers/_form.html.erb
<%= simple_form_for(@passenger) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-inputs">
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/passengers/edit.html.erb
<h1>Edit Passenger</h1>

<%= render 'form', passenger: @passenger %>

app/views/passengers/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Passengers</h1>
  </div>

  <div class="col-sm-6 text-end">
  <%= link_to new_passenger_path, class: 'btn btn-primary' do %>
    Add New Passenger
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    

            <th>Booking</th>
            
          <th></th>
        
      </tr>
    </thead>

    <tbody>
      <% @passengers.each do |passenger| %>
        <%= content_tag :tr, id: dom_id(passenger), class: dom_class(passenger) do %>
          

                      <td><%= passenger.booking_id %></td>
          
          
            <td><%= link_to 'Show', passenger %></td>
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/passengers/new.html.erb
<h1>New passenger</h1>
<%= @passenger_params %>
<%= render 'form', passenger: @passenger %>

app/views/passengers/show.html.erb
<div class="page-header">
  <%= link_to passengers_path, class: 'btn btn-default' do %>
    All Passengers
  <% end %>
  <%= link_to edit_passenger_path(@passenger), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show passenger</h1>
</div>

<dl class="dl-horizontal">
  <dt>Booking:</dt>
  <dd><%= @passenger.booking_id %></dd>
</dl>